version: '3'
services:
  db:
    image: postgres:12.3-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "bhola_dev"
      POSTGRES_DB: "bhola_dev"
  web:
    image: bhola_container_image_dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      RAILS_ENV: development
    depends_on:
      - db
  clockwork:
    image: bhola_container_image_dev
    command: ["bundle", "exec", "clockwork", "clock.rb"]
    environment:
      DB_HOST: db
      RAILS_ENV: development
    depends_on:
      - db
      - web
