## value in days, if the certificate expiry is happening lower than this value
## then the domain owner be notified
test:
  certificate_expiry_threshold: "10"
  check_certificate_job_retrigger_threshold: "86400"
development:
  check_certificate_job_retrigger_threshold: "86400"
  certificate_expiry_threshold: "10"
production:
  check_certificate_job_retrigger_threshold: "86400"
  certificate_expiry_threshold: "10"
